"""empty message

Revision ID: 2067b2571a6f
Revises: 
Create Date: 2023-12-28 21:35:26.962728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2067b2571a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('known_for_department', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=100), nullable=False),
    sa.Column('popularity', sa.String(length=100), nullable=False),
    sa.Column('profile_path', sa.String(length=100), nullable=False),
    sa.Column('known_for', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_language', sa.String(length=120), nullable=False),
    sa.Column('original_title', sa.String(length=100), nullable=False),
    sa.Column('overview', sa.String(length=100), nullable=False),
    sa.Column('popularity', sa.String(length=100), nullable=False),
    sa.Column('poster_path', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('video', sa.String(length=100), nullable=False),
    sa.Column('vote_average', sa.String(length=100), nullable=False),
    sa.Column('vote_count', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_language')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_language', sa.String(length=120), nullable=False),
    sa.Column('original_name', sa.String(length=100), nullable=False),
    sa.Column('overview', sa.String(length=100), nullable=False),
    sa.Column('popularity', sa.String(length=100), nullable=False),
    sa.Column('poster_path', sa.String(length=100), nullable=False),
    sa.Column('first_air_date', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vote_average', sa.String(length=100), nullable=False),
    sa.Column('vote_count', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_language')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movies_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('actors_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actors_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('series')
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
