"""empty message

Revision ID: 92094ae9223a
Revises: 43786b6de78d
Create Date: 2023-12-27 22:19:15.378628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92094ae9223a'
down_revision = '43786b6de78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('serie_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('serie_id')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
