"""empty message

Revision ID: fdf3e3132b07
Revises: d28246a8d027
Create Date: 2024-01-05 23:17:44.819054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf3e3132b07'
down_revision = 'd28246a8d027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('serie_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('serie_id')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
